name: whizz
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  speech_to_text: ^5.6.1
  avatar_glow: ^2.0.2
  highlight_text: ^1.4.1
  translator: ^0.1.7
  flutter_tts: ^3.5.3
  geolocator: ^9.0.1
  geocoding: ^2.0.5
  restart_app: ^1.1.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true



